---
title: "Questionnaire"
author: "Mie Buchhave Ryborg"
date: "11/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(tidyverse, ggplot2, RColorBrewer)

#install.packages("stopwords")

```

```{r}
setwd("~/Dokumenter/AU/5. Bachelor/analysis_e1a")
```

```{r}
files <- list.files(path = "data", pattern = ".csv", full.names = T)

df <- map_dfr(files, read_csv) #loading the data

number_files <- list.files(path = "data_number_id", pattern = ".csv", full.names = T)
df_number <- map_dfr(number_files, read_csv) #loading the data
df_number$participant <- "yw2"

same_id_files <- list.files(path = "data_extra", pattern = ".csv", full.names = T)
same_id_df <- map_dfr(same_id_files, read_csv) #loading the data
same_id_df$participant <- "jb2"


df <- rbind(df, df_number, same_id_df)

df
```

```{r}
colnames(df)[21] <- 'ID'
colnames(df)[22] <- 'age'

```


## Let us look at the questionnaire

```{r}

df_q <- dplyr::select(df,
               ID = ID,
               age = age,
               story = story,
               condition = type_condition,
               question = questions,
               answer = correct,
               response_key = question_resp.keys,
               correct = question_resp.corr,
               rt = question_resp.rt
        
                
)

df_q <- na.omit(df_q)

```

```{r}
correct_story_1 = c("1", "2", "2", "1")
correct_story_2 = c("4", "3", "4", "4")
correct_story_3 = c("1", "1", "4", "3")
correct_story_4 = c("1", "1", "2", "3")
correct_story_5 = c("4", "3", "2", "4")

answer <- c()
q_type <- c()

for (i in 1:length(df_q$question)) {
  if (df_q$question[i] == 'resources/story_1_q_1.png') {
    answer[i] <- correct_story_1[1]
    q_type[i] <- "local"
    df_q$question[i] <- "story_1_q_1"
  } else if (df_q$question[i] == 'resources/story_1_q_2.png') {
    answer[i] <- correct_story_1[2]
    q_type[i] <- "local"
    df_q$question[i] <- "story_1_q_2"
  } else if (df_q$question[i] == 'resources/story_1_q_3.png') {
    answer[i] <- correct_story_1[3]
    q_type[i] <- "local"
    df_q$question[i] <- "story_1_q_3"
  } else if (df_q$question[i] == 'resources/story_1_q_4.png') {
    answer[i] <- correct_story_1[4]
    q_type[i] <- "global"
    df_q$question[i] <- "story_1_q_4"
  } else if (df_q$question[i] == 'resources/story_2_q_1.png') {
    answer[i] <- correct_story_2[1]
    q_type[i] <- "local"
    df_q$question[i] <- "story_2_q_1"
  } else if (df_q$question[i] == 'resources/story_2_q_2.png') {
    answer[i] <- correct_story_2[2]
    q_type[i] <- "local"
    df_q$question[i] <- "story_2_q_2"
  } else if (df_q$question[i] == 'resources/story_2_q_3.png') {
    answer[i] <- correct_story_2[3]
    q_type[i] <- "local"
    df_q$question[i] <- "story_2_q_3"
  } else if (df_q$question[i] == 'resources/story_2_q_4.png') {
    answer[i] <- correct_story_2[4]
    q_type[i] <- "global"
    df_q$question[i] <- "story_2_q_4"
  } else if (df_q$question[i] == 'resources/story_3_q_1.png') {
    answer[i] <- correct_story_3[1]
    q_type[i] <- "local"
    df_q$question[i] <- "story_3_q_1"
  } else if (df_q$question[i] == 'resources/story_3_q_2.png') {
    answer[i] <- correct_story_3[2]
    q_type[i] <- "local"
    df_q$question[i] <- "story_3_q_2"
  } else if (df_q$question[i] == 'resources/story_3_q_3.png') {
    answer[i] <- correct_story_3[3]
    q_type[i] <- "global"
    df_q$question[i] <- "story_3_q_3"
  } else if (df_q$question[i] == 'resources/story_3_q_4.png') {
    answer[i] <- correct_story_3[4]
    q_type[i] <- "local"
    df_q$question[i] <- "story_3_q_4"
  } else if (df_q$question[i] == 'resources/story_4_q_1.png') {
    answer[i] <- correct_story_4[1]
    q_type[i] <- "local"
    df_q$question[i] <- "story_4_q_1"
  } else if (df_q$question[i] == 'resources/story_4_q_2.png') {
    answer[i] <- correct_story_4[2]
    q_type[i] <- "global"
    df_q$question[i] <- "story_4_q_2"
  } else if (df_q$question[i] == 'resources/story_4_q_3.png') {
    answer[i] <- correct_story_4[3]
    q_type[i] <- "local"
    df_q$question[i] <- "story_4_q_3"
  } else if (df_q$question[i] == 'resources/story_4_q_4.png') {
    answer[i] <- correct_story_4[4]
    q_type[i] <- "local"
    df_q$question[i] <- "story_4_q_4"
  } else if (df_q$question[i] == 'resources/story_5_q_1.png') {
    answer[i] <- correct_story_5[1]
    q_type[i] <- "local"
    df_q$question[i] <- "story_5_q_1"
  } else if (df_q$question[i] == 'resources/story_5_q_2.png') {
    answer[i] <- correct_story_5[2]
    q_type[i] <- "local"
    df_q$question[i] <- "story_5_q_2"
  } else if (df_q$question[i] == 'resources/story_5_q_3.png') {
    answer[i] <- correct_story_5[3]
    q_type[i] <- "global"
    df_q$question[i] <- "story_5_q_3"
  } else if (df_q$question[i] == 'resources/story_5_q_4.png') {
    answer[i] <- correct_story_5[4]
    q_type[i] <- "local"
    df_q$question[i] <- "story_5_q_4"
  }

}

df_q$answer_new <- answer
df_q$q_type <- q_type

for (i in 1:length(df_q$answer_new)) {
  if (df_q$response_key[i] == df_q$answer_new[i]) {
    df_q$correct[i] <- 1
  } else {
    df_q$correct[i] <- 0
  }
  
}

df_q$correct <- as.factor(df_q$correct)

```


```{r}
df_q <- df_q %>%
  filter(ID != "xyz679")
```

```{r}
df_q %>%
  filter(ID == "10ml8kl3") %>%
  group_by(q_type) %>%
  summarise(count = n())
```


```{r}
length_df <- length(df_q$ID)
  
df_q %>%
  filter(correct == 1) %>%
  summarise(count = n(), proportion = count/length_df)

```

```{r}
df_q %>%
  group_by(ID, correct) %>%
  summarise(count = n())

```
```{r}

df_percentage <- df_q %>%
  group_by(question, correct, q_type) %>%
  summarise(count = n(), percentage_correct = count / 82 * 100) %>%
  filter(correct == 1)

# Mean percentage of correct across all questions
df_percentage %>%
  group_by(correct) %>%
  summarise(count = n(), mean(percentage_correct), sd(percentage_correct))

df_percentage %>%
  group_by(q_type) %>%
  summarise(count = n(), mean(percentage_correct), sd(percentage_correct))

# Mean percentage of questions with correct below 50%
df_percentage %>%
  filter(percentage_correct < 50) %>%
  group_by(correct) %>%
  summarise(count = n(), mean(percentage_correct), sd(percentage_correct))

df_percentage %>%
  filter(percentage_correct < 50) %>%
  summarise(q_type, mean(percentage_correct), sd(percentage_correct))

# Mean percentage of questions with correct above 50%
df_percentage %>%
  filter(percentage_correct > 50) %>%
  group_by(correct) %>%
  summarise(count = n(), mean(percentage_correct), sd(percentage_correct))

df_percentage %>%
  filter(percentage_correct > 50) %>%
  summarise(q_type, mean(percentage_correct), sd(percentage_correct))


quantile(df_percentage$percentage_correct)

df_percentage %>%
  group_by(q_type) %>%
  summarise(mean(percentage_correct), sd(percentage_correct))

```

```{r}

ggplot(df_q, aes(x = correct, fill = correct)) +
  geom_bar() +
  facet_wrap(~question) +
  ggtitle("Distribution of incorrect (red) and correct (blue) answers for each MCQ") +
  theme_minimal()

```

```{r}

df_q$condition_type <- ifelse(df_q$condition=="control", "control", "bionic")
df_q$is_bionic_condition <- factor(ifelse(df_q$condition=="control", 0, 1))

```

```{r}
question_df <- df_q %>%
  filter(correct == 1) %>%
  group_by(question, q_type) %>%
  summarise(count = n(), mean_rt = mean(rt), sd_rt = sd(rt))

question_df[order(question_df$count), ]

question_df[order(-question_df$mean_rt), ]
```
```{r}

df_q %>%
  filter(correct == "1" ) %>%
  group_by(ID) %>%
  summarise(count = n(), accuracy = count / 20 * 100)

```

```{r}
cor.test(question_df$count, question_df$mean_rt)
```

```{r}

df_correct_count <- df_q %>%
  filter(correct == 1) %>%
  group_by(ID, condition) %>%
  summarise(count = n())

```
```{r}

df_correct_count %>%
  group_by(condition) %>%
  summarise(mean(count))

```



# ANALYSIS OF RQ1C


```{r}

model_1c <- lme4::glmer(data = df_q, correct ~ condition + (1 | ID) + (1 | question), family = binomial(link = "logit"), control = lme4::glmerControl(optimizer="bobyqa"))

```

### MODEL COMPARISON

```{r}

test1_model_1c <- lme4::glmer(data = df_q, correct ~ condition + (1 | ID), family = binomial(link = "logit"))

test2_model_1c <- lme4::glmer(data = df_q, correct ~ condition + (1 | story), family = binomial(link = "logit"))

test3_model_1c <- lme4::glmer(data = df_q, correct ~ condition + (1 + condition | ID) + (1 + condition | question), family = binomial(link = "logit"), control = lme4::glmerControl(optimizer="bobyqa"))


```


```{r}
anova(model_1c, test1_model_1c, test2_model_1c, test3_model_1c)
```

```{r}
summary(model_1c)
```

```{r}


boot::inv.logit(1.2644)

boot::inv.logit(1.2644-0.3623)

boot::inv.logit(1.2644-0.1361)

boot::inv.logit(1.2644-0.2533)

boot::inv.logit(1.2644-0.4657)

```



```{r}
df_q$pred = predict(model_1c, df_q, type="response")
```


```{r}

ggplot(df_q, aes(x = condition, y = pred, fill = condition)) +
  stat_boxplot( aes(condition, pred), geom='errorbar', linetype=1, width=0.2) +
  geom_boxplot(outlier.shape = 4) +
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2) +
  stat_summary(fun.y=mean, geom = "point") +
  labs(title = "Predicted probabilities of correct for each condition \n", y = "Predicted Probability")+
  theme_bw() +
  theme(axis.title.x=element_blank(),
        axis.ticks.x=element_blank(),
        legend.position = "none", 
        plot.title = element_text(hjust = 0.5), 
        plot.subtitle = element_text(hjust = 0.5))

```

```{r}
plot(effects::allEffects(model_1c))

```

